name: league-dashboard

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: league-dashboard-app
    restart: unless-stopped
    ports:
      - "${PORT:-3021}:3021"
    env_file:
      - .env
    command: npm start
